import type { Track } from './types'

const base = import.meta.env.BASE_URL

type StationSource = {
  id: string
  filename: string
  title: string
  description: string
  durationSec: number
  audioFolder: 'studio' | 'lofinity-player'
  artwork: string
  catalogPrefix: 'SR-LF' | 'SR-LP'
  trackIdPrefix: 'lf' | 'lp'
  genre: string
  bpm: number
  energy: number
}

const ARTWORK = {
  alberlan: 'pexels-alberlan-7311921.jpg',
  alexAndrews: 'pexels-alex-andrews-271121-3805983.jpg',
  arnieChou: 'pexels-arnie-chou-304906-1229042.jpg',
  blaque: 'pexels-blaque-x-264516-932638.jpg',
  danielCid: 'pexels-daniel-cid-634838605-17505898.jpg',
  davidPaul: 'pexels-david-paul-2150063702-33313322.jpg',
  dennis32054508: 'pexels-dennisariel-32054508.jpg',
  dennis32880873: 'pexels-dennisariel-32880873.jpg',
  dennis32880874: 'pexels-dennisariel-32880874.jpg',
  dennis33263307: 'pexels-dennisariel-33263307.jpg',
  eberhard1624360: 'pexels-eberhardgross-1624360.jpg',
  eberhard2098427: 'pexels-eberhardgross-2098427.jpg',
  faikackmerd: 'pexels-faikackmerd-1025469.jpg',
  jmueller: 'pexels-jmueller-6444367.jpg',
  luisfe: 'pexels-luisfe-5191926.jpg',
  lum3n: 'pexels-lum3n-44775-167684.jpg',
  matthardy: 'pexels-matthardy-1533720.jpg',
  merlin: 'pexels-merlin-11167645.jpg',
  necatiomerk: 'pexels-necatiomerk-33260303.jpg',
  neilyonamine: 'pexels-neilyonamine-8237959.jpg',
  nicole: 'pexels-nicole-avagliano-1132392-2706654.jpg',
  nivdex: 'pexels-nivdex-796206.jpg',
  pixabay: 'pexels-pixabay-41951.jpg',
  scott30820838: 'pexels-scott-lord-564881271-30820838.jpg',
  scott32511120: 'pexels-scott-lord-564881271-32511120.jpg',
  simon73: 'pexels-simon73-1323550.jpg',
  sliceisop: 'pexels-sliceisop-2873669.jpg',
  toddTrapani: 'pexels-todd-trapani-488382-1420440.jpg',
  umkreisel: 'pexels-umkreisel-app-2832071.jpg',
} as const

/** Lofinity studio sessions — audio in `public/audio/studio/`. */
const LOFI_SOURCES: StationSource[] = [
  {
    id: '01',
    filename: 'lofi_1772339070.wav',
    title: 'Lofi Transmission 01',
    description: 'AI-generated lofi hip hop from the SpaceRadio studio.',
    durationSec: 15,
    audioFolder: 'studio',
    artwork: ARTWORK.faikackmerd,
    catalogPrefix: 'SR-LF',
    trackIdPrefix: 'lf',
    genre: 'lofi-hiphop',
    bpm: 82,
    energy: 3,
  },
  {
    id: '02',
    filename: 'lofi_1772340178.wav',
    title: 'Lofi Transmission 02',
    description: 'AI-generated lofi hip hop from the SpaceRadio studio.',
    durationSec: 15,
    audioFolder: 'studio',
    artwork: ARTWORK.eberhard1624360,
    catalogPrefix: 'SR-LF',
    trackIdPrefix: 'lf',
    genre: 'lofi-hiphop',
    bpm: 82,
    energy: 3,
  },
  {
    id: '03',
    filename: 'lofi_1772341832.wav',
    title: 'Lofi Transmission 03',
    description: 'AI-generated lofi hip hop from the SpaceRadio studio.',
    durationSec: 180,
    audioFolder: 'studio',
    artwork: ARTWORK.pixabay,
    catalogPrefix: 'SR-LF',
    trackIdPrefix: 'lf',
    genre: 'lofi-hiphop',
    bpm: 82,
    energy: 2,
  },
  {
    id: '04',
    filename: 'lofi_1772349745.wav',
    title: 'Lofi Transmission 04',
    description: 'AI-generated lofi hip hop from the SpaceRadio studio.',
    durationSec: 180,
    audioFolder: 'studio',
    artwork: ARTWORK.merlin,
    catalogPrefix: 'SR-LF',
    trackIdPrefix: 'lf',
    genre: 'lofi-hiphop',
    bpm: 82,
    energy: 2,
  },
  {
    id: '05',
    filename: 'lofi_1772401152.wav',
    title: 'Lofi Transmission 05',
    description: 'AI-generated lofi hip hop from the SpaceRadio studio.',
    durationSec: 180,
    audioFolder: 'studio',
    artwork: ARTWORK.neilyonamine,
    catalogPrefix: 'SR-LF',
    trackIdPrefix: 'lf',
    genre: 'lofi-hiphop',
    bpm: 82,
    energy: 2,
  },
  {
    id: '06',
    filename: 'lofi_1772403752.wav',
    title: 'Lofi Transmission 06',
    description: 'AI-generated lofi hip hop from the SpaceRadio studio.',
    durationSec: 60,
    audioFolder: 'studio',
    artwork: ARTWORK.nivdex,
    catalogPrefix: 'SR-LF',
    trackIdPrefix: 'lf',
    genre: 'lofi-hiphop',
    bpm: 82,
    energy: 3,
  },
  {
    id: '07',
    filename: 'lofi_1772414847.wav',
    title: 'Dusty Vinyl Drift',
    description:
      'Studio session: lofi hiphop instrumental, dusty vinyl, mellow jazz chords, boom bap drums, 80 bpm',
    durationSec: 30,
    audioFolder: 'studio',
    artwork: ARTWORK.arnieChou,
    catalogPrefix: 'SR-LF',
    trackIdPrefix: 'lf',
    genre: 'lofi-hiphop',
    bpm: 80,
    energy: 3,
  },
  {
    id: '08',
    filename: 'lofi_1772416766.wav',
    title: 'Minimal Orbit',
    description: 'Studio session: lofi hiphop, minimalist',
    durationSec: 30,
    audioFolder: 'studio',
    artwork: ARTWORK.blaque,
    catalogPrefix: 'SR-LF',
    trackIdPrefix: 'lf',
    genre: 'lofi-hiphop',
    bpm: 82,
    energy: 3,
  },
]

/** lofinity-player catalog — audio in `public/audio/lofinity-player/`. */
const PLAYER_SOURCES: StationSource[] = [
  {
    id: '01',
    filename: 'Breath Between The Worlds.mp3',
    title: 'Breath Between The Worlds',
    description:
      'The liminal rhythm where inhale becomes exhale, and two dimensions press softly together at the seam.',
    durationSec: 188,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.lum3n,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '02',
    filename: 'Celestia I.mp3',
    title: 'Celestia I',
    description:
      'First passage through the outer vault — light bending around ancient stars as consciousness unfolds toward the infinite.',
    durationSec: 469,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.dennis32880873,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 2,
  },
  {
    id: '03',
    filename: 'Celestia II.mp3',
    title: 'Celestia II',
    description:
      'The second arc deeper into luminous fields, where the sky forgets its own edges and becomes pure frequency.',
    durationSec: 244,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.toddTrapani,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '04',
    filename: 'Driving 111.mp3',
    title: 'Driving 111',
    description:
      'A hypnotic pulse through infinite corridors of neon and stardust, where velocity itself becomes a form of meditation.',
    durationSec: 367,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.simon73,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '05',
    filename: 'Eros Orchard.mp3',
    title: 'Eros Orchard',
    description:
      'A garden blooming at the edge of desire and creation, where sacred fruit falls upward into the arms of the cosmos.',
    durationSec: 230,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.luisfe,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '06',
    filename: 'In reach of meaning.mp3',
    title: 'In reach of meaning',
    description:
      'Fingers outstretched toward the ineffable — that trembling, suspended moment just before understanding arrives.',
    durationSec: 217,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.dennis32880874,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '07',
    filename: 'Knocking at Heaven.mp3',
    title: 'Knocking at Heaven',
    description:
      'A gentle percussion against the membrane of the infinite, reverberating outward through galaxies waiting to open.',
    durationSec: 203,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.alberlan,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '08',
    filename: 'Kosmographica.mp3',
    title: 'Kosmographica',
    description:
      'The living atlas of the universe — each beat a continent, each melody a star system charted in pure sound.',
    durationSec: 317,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.sliceisop,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '09',
    filename: 'Life is Vibration.mp3',
    title: 'Life is Vibration',
    description:
      'The fundamental truth humming beneath all matter — atoms, minds, and stars all singing the same secret frequency.',
    durationSec: 323,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.alexAndrews,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '10',
    filename: 'Light in mind.mp3',
    title: 'Light in mind',
    description:
      'Photons threading through neural corridors, illuminating the vast interior landscape of awareness one synapse at a time.',
    durationSec: 264,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.danielCid,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '11',
    filename: 'Maxsoft.mp3',
    title: 'Maxsoft',
    description:
      'Texture at the threshold of touch and thought — the softest frequency the cosmos can whisper without dissolving into silence.',
    durationSec: 214,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.davidPaul,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '12',
    filename: 'Nondualizer.mp3',
    title: 'Nondualizer',
    description:
      'A sonic dissolution of all boundaries, where subject and object merge into a single, seamless, flowing field.',
    durationSec: 279,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.dennis32054508,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '13',
    filename: 'On The Temple Roof.mp3',
    title: 'On The Temple Roof',
    description:
      'Above the sacred chamber, the stars press close enough to hear — devotion rising like incense smoke into the dark.',
    durationSec: 282,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.dennis33263307,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '14',
    filename: 'Orbitron.mp3',
    title: 'Orbitron',
    description:
      'A precise and eternal mechanical orbit, gears turning inside planets turning inside the great clockwork of galaxies.',
    durationSec: 230,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.eberhard2098427,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '15',
    filename: 'Outworld.mp3',
    title: 'Outworld',
    description:
      'Beyond the edge of every map, where frequency becomes geography and sound becomes the terrain of unexplored dimensions.',
    durationSec: 223,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.jmueller,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '16',
    filename: 'Panentheon.mp3',
    title: 'Panentheon',
    description:
      'A pantheon that holds all worlds within it — every deity a frequency, every prayer a waveform returned as melody.',
    durationSec: 369,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.matthardy,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 2,
  },
  {
    id: '17',
    filename: 'Putting down.mp3',
    title: 'Putting down',
    description:
      'The sacred art of release — setting down the weight of accumulated time and drifting into weightless, boundless presence.',
    durationSec: 279,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.necatiomerk,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '18',
    filename: 'Rainbow Arrows.mp3',
    title: 'Rainbow Arrows',
    description:
      'Chromatic shafts of light launched across the sky, each wavelength a different prayer finding its mark in the dark.',
    durationSec: 329,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.nicole,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '19',
    filename: 'Rewinding Time.mp3',
    title: 'Rewinding Time',
    description:
      'The tape unspools backward through memory, through birth, through stardust and the first silence before the first sound.',
    durationSec: 196,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.scott30820838,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '20',
    filename: 'Signals from Somewhere.mp3',
    title: 'Signals from Somewhere',
    description:
      'Transmissions arriving from coordinates unknown — meaning encoded in the luminous space between notes.',
    durationSec: 243,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.scott32511120,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '21',
    filename: 'Starfields in Bloom.mp3',
    title: 'Starfields in Bloom',
    description:
      'A garden of suns flowering across the dark, pollinated by wandering comets and the slow breath of cosmic wind.',
    durationSec: 300,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.umkreisel,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 2,
  },
  {
    id: '22',
    filename: 'Stone Circuits.mp3',
    title: 'Stone Circuits',
    description:
      'Ancient architecture pulsing with electricity — the lithic and the digital converging across a billion years of time.',
    durationSec: 300,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.lum3n,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 2,
  },
  {
    id: '23',
    filename: 'Stratomind.mp3',
    title: 'Stratomind',
    description:
      'A mind expanded to the curvature of a stratosphere, dreaming in weather systems and tectonic whispers.',
    durationSec: 268,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.dennis32880873,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '24',
    filename: 'Textures of feelings.mp3',
    title: 'Textures of feelings',
    description:
      'The tactile surface of emotion — each sensation a different fabric woven from the threads of lived light.',
    durationSec: 252,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.toddTrapani,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '25',
    filename: 'There is a voice in you.mp3',
    title: 'There is a voice in you',
    description:
      'The inner resonance that never ceases — older than memory, quieter than silence, vaster than any sky.',
    durationSec: 259,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.simon73,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
  {
    id: '26',
    filename: '息がある。(Iki ga aru)  There is Breath.mp3',
    title: '息がある。(Iki ga aru) — There is Breath',
    description:
      'The Japanese art of breath as being — every exhalation a universe released, every inhalation a cosmos born.',
    durationSec: 252,
    audioFolder: 'lofinity-player',
    artwork: ARTWORK.luisfe,
    catalogPrefix: 'SR-LP',
    trackIdPrefix: 'lp',
    genre: 'space-ambient',
    bpm: 72,
    energy: 3,
  },
]

const ALL_SOURCES = [...LOFI_SOURCES, ...PLAYER_SOURCES]

const MISSION_SLUGS = [
  'deep-orbit',
  'demo-flight',
  'mars-relay',
  'jwst',
  'voyager-tribute',
  'artemis',
  'deep-orbit',
  'demo-flight',
] as const

function stationAudioUrl(folder: string, filename: string): string {
  const encoded = filename
    .split('/')
    .map((part) => encodeURIComponent(part))
    .join('/')
  return `${base}audio/${folder}/${encoded}`
}

function trackArtworkUrl(filename: string): string {
  return `${base}artwork/tracks/${encodeURIComponent(filename)}`
}

export const STATION_EPOCH_MS = Math.floor(1772339072.8278098 * 1000)

export const stationTracks: Track[] = ALL_SOURCES.map((source, index) => ({
  id: `${source.trackIdPrefix}-${source.id}`,
  title: source.title,
  artist: 'SpaceRadio Originals',
  catalogId: `${source.catalogPrefix}-${source.id}`,
  durationSec: source.durationSec,
  bpm: source.bpm,
  genre: source.genre,
  energy: source.energy,
  missionSlug: MISSION_SLUGS[index % MISSION_SLUGS.length],
  curatorNote: source.description,
  demoAudioUrl: stationAudioUrl(source.audioFolder, source.filename),
  artworkUrl: trackArtworkUrl(source.artwork),
}))

export function getStationPlaylistDurationSec(): number {
  return stationTracks.reduce((sum, track) => sum + track.durationSec, 0)
}

export function hasStationPlaylist(): boolean {
  return stationTracks.length > 0
}
