/** Normalize body copy so Barlow renders cleanly (no missing-glyph question marks). */
export function toDisplayText(text: string): string {
  let s = text
    .replace(/\uFFFD/g, '')
    .replace(/\u2014/g, ' - ')
    .replace(/\u2013/g, '-')
    .replace(/\u2192/g, ' -> ')
    .replace(/\u00B7/g, ' · ')
    .replace(/\u2248/g, '~')
    .replace(/\u226A/g, '<<')
    .replace(/\u2273/g, '>=')
    .replace(/\u2265/g, '>=')
    .replace(/\u00D7/g, ' x ')
    .replace(/\u03C0/g, 'pi')
    .replace(/\u03BB/g, 'lambda')
    .replace(/\u03B8/g, 'theta')
    .replace(/\u03B7/g, 'eta')
    .replace(/\u03C4/g, 'tau')
    .replace(/\u2299/g, 'Sun')
    .replace(/\u2070/g, '^0')
    .replace(/\u00B9/g, '^1')
    .replace(/\u00B2/g, '^2')
    .replace(/\u00B3/g, '^3')
    .replace(/\u2074/g, '^4')
    .replace(/\u2075/g, '^5')
    .replace(/\u2076/g, '^6')
    .replace(/\u2077/g, '^7')
    .replace(/\u2078/g, '^8')
    .replace(/\u2079/g, '^9')
    .replace(/\u207B/g, '^-')
    .replace(/\u2080/g, '0')
    .replace(/\u20AC/g, 'EUR ')

  s = s
    .replace(/Math \? physics \? engineering \? culture/g, 'Math -> physics -> engineering -> culture')
    .replace(/Earth\?Sun\?target/g, 'Earth -> Sun -> target')
    .replace(/Phase-1\?Phase-2/g, 'Phase-1 -> Phase-2')
    .replace(
      /Civilization A \? local seed \? regional cluster \? galactic archive layer \? future civilization/g,
      'Civilization A -> local seed -> regional cluster -> galactic archive layer -> future civilization',
    )
    .replace(/P_overlap \? 2L\/W/g, 'P_overlap ~ 2L/W')
    .replace(/when L \? W/g, 'when L << W')
    .replace(/L = 10\? yr/g, 'L = 10^4 yr')
    .replace(/W = 10\? yr/g, 'W = 10^10 yr')
    .replace(/10\? yr/g, '10^4 yr')
    .replace(/10\?\?/g, '10^13')
    .replace(/2\uFFFD10\?\?/g, '2x10^-6')
    .replace(/2\?10\?\?/g, '2x10^-6')
    .replace(/210\?\?/g, '2x10^-6')
    .replace(/\? 1 \(design goal\)/g, '~1 (design goal)')
    .replace(/\? 1'/g, "~1'")
    .replace(/1 \? \(1\?s\)/g, '1 - (1-s)')
    .replace(/1 \? \(1/g, '1 - (1')
    .replace(/Levels 1\?5/g, 'Levels 1-5')
    .replace(/0\?10 yr/g, '0-10 yr')
    .replace(/10\?30 yr/g, '10-30 yr')
    .replace(/30\?80 yr/g, '30-80 yr')
    .replace(/50\?150 yr/g, '50-150 yr')
    .replace(/100 yr\?10\? yr/g, '100 yr-10^6 yr')
    .replace(/\$70M\?\$250M/g, '$70M-$250M')
    .replace(/\$2B\?\$10B/g, '$2B-$10B')
    .replace(/\$10B\?\$100B/g, '$10B-$100B')
    .replace(/\$1B\?\$5B/g, '$1B-$5B')
    .replace(/\$300M\?\$1\.5B/g, '$300M-$1.5B')
    .replace(/WP-(\d) \? /g, 'WP-$1 - ')
    .replace(/Phase (\d) \? /g, 'Phase $1 - ')
    .replace(/wavelength \? /g, 'wavelength lambda ')
    .replace(/G \? /g, 'G ~ ')
    .replace(/EIRP \? /g, 'EIRP ~ ')
    .replace(/Integration \?/g, 'Integration tau')
    .replace(/\(\?\/B\)\^/g, '(tau/B)^(1/4)')
    .replace(/10\? s/g, '10^4 s')
    .replace(/4\?R/g, '4pi R^2')
    .replace(/4\? /g, '4pi ')
    .replace(/1\/R\?/g, '1/R^2')
    .replace(/R\?/g, 'R^2')
    .replace(/~\?10/g, '>=10')
    .replace(/\?10 years/g, '>=10 years')
    .replace(/~10\?\? W/g, '~10^10 W')
    .replace(/~6\?10\?\? W/g, '~6x10^12 W')
    .replace(/~4\?10\?\? W/g, '~4x10^17 W')
    .replace(/~10\? W/g, '~10^10 W')
    .replace(/Earth\?Sun/g, 'Earth -> Sun')
    .replace(/d \? 5/g, 'd ~ 5')
    .replace(/v \? 0\.05/g, 'v >= 0.05')
    .replace(/N\? /g, 'N0 ')
    .replace(/10\?\? yr/g, '10^-6 yr')
    .replace(/10\? yr/g, '10^6 yr')
    .replace(/s \? e/g, 's ~ e')
    .replace(/e\?\?/g, 'e^-1')
    .replace(/~10\?/g, '~10^7')
    .replace(/10\?\?10\?/g, '10^7-10^8')
    .replace(/ \? /g, ' - ')

  return s.replace(/  +/g, ' ').trim()
}
